(cl:defpackage blinky-msg
  (:use )
  (:export
   "<FACEFEEDBACK>"
   "FACEFEEDBACK"
   "<FACEACTIONFEEDBACK>"
   "FACEACTIONFEEDBACK"
   "<FACEACTIONRESULT>"
   "FACEACTIONRESULT"
   "<FACEACTION>"
   "FACEACTION"
   "<FACEGOAL>"
   "FACEGOAL"
   "<FACEACTIONGOAL>"
   "FACEACTIONGOAL"
   "<FACERESULT>"
   "FACERESULT"
  ))

