; Auto-generated. Do not edit!


(cl:in-package blinky-msg)


;//! \htmlinclude FaceResult.msg.html

(cl:defclass <FaceResult> (roslisp-msg-protocol:ros-message)
  ((choice
    :reader choice
    :initarg :choice
    :type cl:string
    :initform ""))
)

(cl:defclass FaceResult (<FaceResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FaceResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FaceResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name blinky-msg:<FaceResult> is deprecated: use blinky-msg:FaceResult instead.")))

(cl:ensure-generic-function 'choice-val :lambda-list '(m))
(cl:defmethod choice-val ((m <FaceResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader blinky-msg:choice-val is deprecated.  Use blinky-msg:choice instead.")
  (choice m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FaceResult>) ostream)
  "Serializes a message object of type '<FaceResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'choice))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'choice))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FaceResult>) istream)
  "Deserializes a message object of type '<FaceResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'choice) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'choice) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FaceResult>)))
  "Returns string type for a message object of type '<FaceResult>"
  "blinky/FaceResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FaceResult)))
  "Returns string type for a message object of type 'FaceResult"
  "blinky/FaceResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FaceResult>)))
  "Returns md5sum for a message object of type '<FaceResult>"
  "bc1eb9e6d4887ec14b3959b9a2e31564")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FaceResult)))
  "Returns md5sum for a message object of type 'FaceResult"
  "bc1eb9e6d4887ec14b3959b9a2e31564")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FaceResult>)))
  "Returns full string definition for message of type '<FaceResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string choice # The selected choice, if applicable.~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FaceResult)))
  "Returns full string definition for message of type 'FaceResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string choice # The selected choice, if applicable.~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FaceResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'choice))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FaceResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FaceResult
    (cl:cons ':choice (choice msg))
))
