; Auto-generated. Do not edit!


(cl:in-package blinky-msg)


;//! \htmlinclude FaceActionGoal.msg.html

(cl:defclass <FaceActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type blinky-msg:FaceGoal
    :initform (cl:make-instance 'blinky-msg:FaceGoal)))
)

(cl:defclass FaceActionGoal (<FaceActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FaceActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FaceActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name blinky-msg:<FaceActionGoal> is deprecated: use blinky-msg:FaceActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <FaceActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader blinky-msg:header-val is deprecated.  Use blinky-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <FaceActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader blinky-msg:goal_id-val is deprecated.  Use blinky-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <FaceActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader blinky-msg:goal-val is deprecated.  Use blinky-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FaceActionGoal>) ostream)
  "Serializes a message object of type '<FaceActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FaceActionGoal>) istream)
  "Deserializes a message object of type '<FaceActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FaceActionGoal>)))
  "Returns string type for a message object of type '<FaceActionGoal>"
  "blinky/FaceActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FaceActionGoal)))
  "Returns string type for a message object of type 'FaceActionGoal"
  "blinky/FaceActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FaceActionGoal>)))
  "Returns md5sum for a message object of type '<FaceActionGoal>"
  "1efaad4b7402c94375e4349d897c3b40")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FaceActionGoal)))
  "Returns md5sum for a message object of type 'FaceActionGoal"
  "1efaad4b7402c94375e4349d897c3b40")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FaceActionGoal>)))
  "Returns full string definition for message of type '<FaceActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%FaceGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: blinky/FaceGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string display_type # See display type constants.~%string h1_text # Large, headline text.~%string h2_text # Regular-sized text.~%string question # The question to ask to the user.~%string[] choices # Choices for multiple choice question.~%~%# Display types.~%string DEFAULT = default~%string DISPLAY_MESSAGE = displayMessage~%string ASK_CHOICE = askMultipleChoice~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FaceActionGoal)))
  "Returns full string definition for message of type 'FaceActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%FaceGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: blinky/FaceGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string display_type # See display type constants.~%string h1_text # Large, headline text.~%string h2_text # Regular-sized text.~%string question # The question to ask to the user.~%string[] choices # Choices for multiple choice question.~%~%# Display types.~%string DEFAULT = default~%string DISPLAY_MESSAGE = displayMessage~%string ASK_CHOICE = askMultipleChoice~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FaceActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FaceActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'FaceActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
