; Auto-generated. Do not edit!


(cl:in-package blinky-msg)


;//! \htmlinclude FaceFeedback.msg.html

(cl:defclass <FaceFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass FaceFeedback (<FaceFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FaceFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FaceFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name blinky-msg:<FaceFeedback> is deprecated: use blinky-msg:FaceFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FaceFeedback>) ostream)
  "Serializes a message object of type '<FaceFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FaceFeedback>) istream)
  "Deserializes a message object of type '<FaceFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FaceFeedback>)))
  "Returns string type for a message object of type '<FaceFeedback>"
  "blinky/FaceFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FaceFeedback)))
  "Returns string type for a message object of type 'FaceFeedback"
  "blinky/FaceFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FaceFeedback>)))
  "Returns md5sum for a message object of type '<FaceFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FaceFeedback)))
  "Returns md5sum for a message object of type 'FaceFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FaceFeedback>)))
  "Returns full string definition for message of type '<FaceFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FaceFeedback)))
  "Returns full string definition for message of type 'FaceFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FaceFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FaceFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FaceFeedback
))
