port: /dev/dspbot
#port: /dev/ttyUSB0
baud: 115200
timeout: 0.1
rate: 50
sensorstate_rate: 10

useImu: False
use_base_controller: True
base_controller_rate: 10

# For a robot that uses base_footprint, change base_frame to base_footprint
#base_frame: base_link
base_frame: base_footprint

# === Robot drivetrain parameters
wheel_diameter: 0.105
wheel_track: 0.212
encoder_resolution: 44
gear_reduction: 90
motors_reversed: False

# === PID parameters
Kp: 0.8
Kd: 0.0
Ki: 1.2
Ko: 0
accel_limit: 1.0
