#!/bin/bash

log_file=/tmp/dspbot-upstart.log
DATE=`date`

source /opt/ros/kinetic/setup.bash
source /home/dspbot_ws/devel/setup.bash

interface=wlan0
echo "$DATE: dspbot-start on interface $interface" >> $log_file

export ROS_IP=`ifconfig $interface | grep -o 'inet addr:[^ ]*' | cut -d: -f2`

echo "$DATE: dspbot-start setting ROS_IP=$ROS_IP" >> $log_file

if [ "$ROS_IP" = "" ]; then
    echo "$DATE: dspbot-start can't run with empty ROS_IP." >> $log_file
    exit 1
fi

roslaunch  dspbot_bringup  minimal.launch
