(cl:defpackage exploration_msgs-msg
  (:use )
  (:export
   "<EXPLOREACTIONGOAL>"
   "EXPLOREACTIONGOAL"
   "<EXPLOREACTIONFEEDBACK>"
   "EXPLOREACTIONFEEDBACK"
   "<EXPLOREACTION>"
   "EXPLOREACTION"
   "<EXPLORERESULT>"
   "EXPLORERESULT"
   "<EXPLOREACTIONRESULT>"
   "EXPLOREACTIONRESULT"
   "<EXPLOREGOAL>"
   "EXPLOREGOAL"
   "<EXPLOREFEEDBACK>"
   "EXPLOREFEEDBACK"
  ))

